use std::collections::BTreeMap;

use matrix_sdk_crypto::{DecryptionSettings, EncryptionSyncChanges, TrustRequirement};
use ruma::{OneTimeKeyAlgorithm, UInt, api::client::sync::sync_events::DeviceLists};
use ruma::{events::AnyToDeviceEvent, serde::Raw};

use super::CryptoManager;

impl CryptoManager {
    /// Process to-device events received via appservice transactions (MSC2409).
    ///
    /// These events contain Olm key exchange messages needed for E2EE.
    /// Acquires a write lock to prevent concurrent encrypt operations.
    pub async fn receive_sync_changes(
        &self,
        to_device_events: Vec<Raw<AnyToDeviceEvent>>,
        changed_devices: &DeviceLists,
        one_time_keys_counts: &BTreeMap<OneTimeKeyAlgorithm, UInt>,
        unused_fallback_keys: Option<&[OneTimeKeyAlgorithm]>,
    ) -> anyhow::Result<()> {
        let _guard = self.lock.write().await;

        let decryption_settings = DecryptionSettings {
            sender_device_trust_requirement: TrustRequirement::Untrusted,
        };

        self.machine
            .receive_sync_changes(
                EncryptionSyncChanges {
                    to_device_events,
                    changed_devices,
                    one_time_keys_counts,
                    unused_fallback_keys,
                    next_batch_token: None,
                },
                &decryption_settings,
            )
            .await?;

        // Process any outgoing requests generated by the sync changes.
        self.process_outgoing_requests().await?;

        Ok(())
    }
}
